# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spdkcsi-cm
data:
  # rpcURL: spdk json rpc target
  # targetType: nvme-rdma, nvme-tcp, iscsi
  # targetAddr: target service IP
  # sma.server: URL to connect the SMA server on every cluster node,
  #             http://IPADDR:PORT
  #             unix:///path/and/sma.sock
  config.json: |-
    {
      "nodes": [
        {
          "name": "localhost",
          "rpcURL": "http://127.0.0.1:9009",
          "targetType": "nvme-tcp",
          "targetAddr": "127.0.0.1"
        }
      ],
      "sma": {
        "server": "127.0.0.1:5114"
      }
    }
